declare const classNames: {
  readonly balance: "balance";
  readonly balance__value: "balance__value";
  readonly balance__action: "balance__action";
  readonly btn: "btn";
  readonly "deposit-form__nav": "deposit-form__nav";
  readonly "nav-link": "nav-link";
  readonly active: "active";
  readonly "little-label": "little-label";
  readonly "items-credit": "items-credit";
  readonly "items-credit__icon": "items-credit__icon";
  readonly "bank-name-input": "bank-name-input";
  readonly "input-prepend": "input-prepend";
  readonly "bank-logo": "bank-logo";
  readonly input: "input";
  readonly "iban-text": "iban-text";
  readonly "table-view": "table-view";
  readonly "crypto-img": "crypto-img";
  readonly "crypto-name": "crypto-name";
  readonly "silver-button": "silver-button";
  readonly "transaction-button": "transaction-button";
  readonly "lir-icon": "lir-icon";
  readonly "english-number": "english-number";
};
export = classNames;
