declare const classNames: {
  readonly wallet: "wallet";
  readonly wallet__item: "wallet__item";
  readonly wallet__item__icon: "wallet__item__icon";
  readonly wallet__item__title: "wallet__item__title";
  readonly wallet__item__subtitle: "wallet__item__subtitle";
  readonly wallet__item__price: "wallet__item__price";
  readonly wallet__item__actions: "wallet__item__actions";
  readonly "available-balance": "available-balance";
  readonly "usdt-box": "usdt-box";
  readonly "lir-box": "lir-box";
  readonly "wallet__loading--item": "wallet__loading--item";
  readonly "deposit-form__nav": "deposit-form__nav";
  readonly "nav-link": "nav-link";
  readonly active: "active";
  readonly "little-label": "little-label";
  readonly "items-credit": "items-credit";
  readonly "items-credit__icon": "items-credit__icon";
  readonly transactions: "transactions";
  readonly tabs: "tabs";
  readonly tabs__item: "tabs__item";
  readonly wallet__item_title: "wallet__item_title";
  readonly wallet__item_icon: "wallet__item_icon";
  readonly hide: "hide";
};
export = classNames;
