declare const classNames: {
  readonly wrapper: "wrapper";
  readonly header: "header";
  readonly logo: "logo";
  readonly confidence: "confidence";
  readonly container: "container";
  readonly card: "card";
  readonly "card-body": "card-body";
  readonly title: "title";
  readonly text: "text";
  readonly form: "form";
  readonly submit: "submit";
  readonly link: "link";
  readonly terms: "terms";
  readonly already: "already";
  readonly forgotLink: "forgotLink";
  readonly "phone-number": "phone-number";
  readonly "otp-container": "otp-container";
  readonly "otp-input": "otp-input";
  readonly "custom-header": "custom-header";
};
export = classNames;
